# -*- coding: utf-8 -*-
"""TEXT_GENARATION

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UGm0JYj9gffucmoK6XokBcbLa_TelffY
"""

!pip install transformers torch

from transformers import pipeline

#Load text generation model (GenAI)
generator = pipeline(
    "text-generation",
    model="gpt2"
)

#Input prompt
prompt= "Importance of Hackathons for securing internships"

#Generate text
result= generator(prompt, max_length=50, num_return_sequences=1)

print("AI Generated Text:")
print(result[0]['generated_text'])